/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientapp;

import java.sql.*;
import java.time.Clock;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author buwaneka
 */
public class ClientSide extends javax.swing.JFrame {

    EmployeeService_Service web = new EmployeeService_Service();
    final EmployeeService service = web.getEmployeeServicePort();
    
    CustomerService_Service webCustomer = new CustomerService_Service();
    final CustomerService cService = webCustomer.getCustomerServicePort();
    
    
    /**
     * Creates new form ClientSide
     */
    public ClientSide() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        resetBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        loginSuccessPanel = new javax.swing.JPanel();
        displayName = new javax.swing.JLabel();
        manageEmployees = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        manageCustBtn = new javax.swing.JButton();
        manageEmpPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        empTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        addEmpBtn = new javax.swing.JButton();
        delEmpBtn = new javax.swing.JButton();
        modifyEmpBtn = new javax.swing.JButton();
        saveEmpBtn = new javax.swing.JButton();
        CreateNewEmployee = new javax.swing.JPanel();
        lblEmpFullName = new javax.swing.JLabel();
        lblEmpPossition = new javax.swing.JLabel();
        lblEmpUserName = new javax.swing.JLabel();
        lblEmpPassword = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtEmployeePosition = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        psswrdFieldEmployee = new javax.swing.JPasswordField();
        btnCreateEmployee = new javax.swing.JButton();
        btnToEmployeePage = new javax.swing.JButton();
        createEmpResetBtn = new javax.swing.JButton();
        customerListPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        custListTable = new javax.swing.JTable();
        delCusBtn = new javax.swing.JButton();
        addCusBtn = new javax.swing.JButton();
        viewCusBtn = new javax.swing.JButton();
        addCusPanel = new javax.swing.JPanel();
        lblCusFullName = new javax.swing.JLabel();
        lblCusAddress = new javax.swing.JLabel();
        lblCusBirthDay = new javax.swing.JLabel();
        lblCusMobile = new javax.swing.JLabel();
        lblCusAccountType = new javax.swing.JLabel();
        lblCusEMail = new javax.swing.JLabel();
        lblCusAccountNumber = new javax.swing.JLabel();
        lblCusSortCode = new javax.swing.JLabel();
        lblCusBalance = new javax.swing.JLabel();
        lblCusCard = new javax.swing.JLabel();
        btnRetrieveValues = new javax.swing.JButton();
        txtCustFullName = new javax.swing.JTextField();
        txtCustBirthDay = new javax.swing.JTextField();
        txtCustAddress = new javax.swing.JTextField();
        txtCustMobile = new javax.swing.JTextField();
        txtCustEmail = new javax.swing.JTextField();
        txtCustAccountType = new javax.swing.JTextField();
        txtCustAccountNumber = new javax.swing.JTextField();
        txtCustSortCode = new javax.swing.JTextField();
        txtCustBalance = new javax.swing.JTextField();
        txtCustCard = new javax.swing.JTextField();
        btnToCustomerPage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabel1.setText("Username : ");

        username.setText("buwa");
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel2.setText("Password : ");

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        password.setText("1234");
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(loginPanelLayout.createSequentialGroup()
                            .addComponent(resetBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(loginBtn))
                        .addGroup(loginPanelLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetBtn)
                    .addComponent(loginBtn))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        getContentPane().add(loginPanel, "card2");

        displayName.setText("Employee");

        manageEmployees.setText("Manage Employees");
        manageEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeesActionPerformed(evt);
            }
        });

        logOutBtn.setText("Log out");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        manageCustBtn.setText("Manage Customers");
        manageCustBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginSuccessPanelLayout = new javax.swing.GroupLayout(loginSuccessPanel);
        loginSuccessPanel.setLayout(loginSuccessPanelLayout);
        loginSuccessPanelLayout.setHorizontalGroup(
            loginSuccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginSuccessPanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(loginSuccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manageEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(manageCustBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(283, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginSuccessPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginSuccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginSuccessPanelLayout.createSequentialGroup()
                        .addComponent(displayName)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginSuccessPanelLayout.createSequentialGroup()
                        .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        loginSuccessPanelLayout.setVerticalGroup(
            loginSuccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginSuccessPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayName)
                .addGap(46, 46, 46)
                .addComponent(manageEmployees)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageCustBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addComponent(logOutBtn)
                .addGap(14, 14, 14))
        );

        getContentPane().add(loginSuccessPanel, "card3");

        empTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        empTable.setEnabled(false);
        empTable.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                empTableInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane1.setViewportView(empTable);

        jLabel3.setText("Employee List");

        addEmpBtn.setText("Add Employee");
        addEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmpBtnActionPerformed(evt);
            }
        });

        delEmpBtn.setText("Delete Employee");
        delEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delEmpBtnActionPerformed(evt);
            }
        });

        modifyEmpBtn.setText("Modify");
        modifyEmpBtn.setDefaultCapable(false);
        modifyEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyEmpBtnActionPerformed(evt);
            }
        });

        saveEmpBtn.setText("Save");
        saveEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEmpBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manageEmpPanelLayout = new javax.swing.GroupLayout(manageEmpPanel);
        manageEmpPanel.setLayout(manageEmpPanelLayout);
        manageEmpPanelLayout.setHorizontalGroup(
            manageEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageEmpPanelLayout.createSequentialGroup()
                .addGroup(manageEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageEmpPanelLayout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel3))
                    .addGroup(manageEmpPanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(manageEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(manageEmpPanelLayout.createSequentialGroup()
                                .addComponent(addEmpBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(delEmpBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modifyEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveEmpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        manageEmpPanelLayout.setVerticalGroup(
            manageEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageEmpPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(manageEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEmpBtn)
                    .addComponent(delEmpBtn)
                    .addComponent(modifyEmpBtn)
                    .addComponent(saveEmpBtn))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        getContentPane().add(manageEmpPanel, "card4");

        CreateNewEmployee.setBorder(javax.swing.BorderFactory.createTitledBorder("New Employee"));

        lblEmpFullName.setText("Full Name");

        lblEmpPossition.setText("Position");

        lblEmpUserName.setText("User Name");

        lblEmpPassword.setText("Password");

        btnCreateEmployee.setText("Create");
        btnCreateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEmployeeActionPerformed(evt);
            }
        });

        btnToEmployeePage.setText("Back");
        btnToEmployeePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToEmployeePageActionPerformed(evt);
            }
        });

        createEmpResetBtn.setText("Reset");
        createEmpResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmpResetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreateNewEmployeeLayout = new javax.swing.GroupLayout(CreateNewEmployee);
        CreateNewEmployee.setLayout(CreateNewEmployeeLayout);
        CreateNewEmployeeLayout.setHorizontalGroup(
            CreateNewEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateNewEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreateNewEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEmpFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmpPossition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmpUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(lblEmpPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(CreateNewEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFullName)
                    .addComponent(psswrdFieldEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(txtUserName)
                    .addComponent(txtEmployeePosition)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateNewEmployeeLayout.createSequentialGroup()
                        .addComponent(btnToEmployeePage)
                        .addGap(18, 18, 18)
                        .addComponent(createEmpResetBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreateEmployee)))
                .addContainerGap())
        );
        CreateNewEmployeeLayout.setVerticalGroup(
            CreateNewEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateNewEmployeeLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(CreateNewEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpFullName)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(CreateNewEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpPossition)
                    .addComponent(txtEmployeePosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(CreateNewEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(CreateNewEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmpPassword)
                    .addComponent(psswrdFieldEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateNewEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateEmployee)
                    .addGroup(CreateNewEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnToEmployeePage)
                        .addComponent(createEmpResetBtn)))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        getContentPane().add(CreateNewEmployee, "card5");

        custListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(custListTable);

        delCusBtn.setText("Delete Customer");
        delCusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delCusBtnActionPerformed(evt);
            }
        });

        addCusBtn.setText("Add Customer");
        addCusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCusBtnActionPerformed(evt);
            }
        });

        viewCusBtn.setText("View Selected Customer");
        viewCusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCusBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerListPanelLayout = new javax.swing.GroupLayout(customerListPanel);
        customerListPanel.setLayout(customerListPanelLayout);
        customerListPanelLayout.setHorizontalGroup(
            customerListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerListPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(customerListPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(delCusBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewCusBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addCusBtn)
                .addGap(28, 28, 28))
        );
        customerListPanelLayout.setVerticalGroup(
            customerListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerListPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(customerListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delCusBtn)
                    .addComponent(addCusBtn)
                    .addComponent(viewCusBtn))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(customerListPanel, "card6");

        addCusPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer Details"));

        lblCusFullName.setText("Full Name");

        lblCusAddress.setText("Address");

        lblCusBirthDay.setText("Birth Day");

        lblCusMobile.setText("Mobile");

        lblCusAccountType.setText("Account Type");

        lblCusEMail.setText("E-Mail");

        lblCusAccountNumber.setText("Account Number");

        lblCusSortCode.setText("Sort Code");

        lblCusBalance.setText("Balance");

        lblCusCard.setText("Card");

        btnRetrieveValues.setText("Add Customer");
        btnRetrieveValues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrieveValuesActionPerformed(evt);
            }
        });

        txtCustFullName.setText(" ");
        txtCustFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustFullNameActionPerformed(evt);
            }
        });

        txtCustBirthDay.setText(" ");

        txtCustAddress.setText("   ");

        txtCustMobile.setText(" ");

        txtCustEmail.setText(" ");

        txtCustAccountType.setText(" ");

        txtCustAccountNumber.setText(" ");

        txtCustSortCode.setText(" ");

        txtCustBalance.setText(" ");

        txtCustCard.setText(" ");

        btnToCustomerPage.setText("Back");
        btnToCustomerPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToCustomerPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addCusPanelLayout = new javax.swing.GroupLayout(addCusPanel);
        addCusPanel.setLayout(addCusPanelLayout);
        addCusPanelLayout.setHorizontalGroup(
            addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCusPanelLayout.createSequentialGroup()
                        .addComponent(btnToCustomerPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRetrieveValues)
                        .addContainerGap())
                    .addGroup(addCusPanelLayout.createSequentialGroup()
                        .addGroup(addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCusAccountNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCusFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCusBirthDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCusAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCusMobile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCusEMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCusAccountType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCusSortCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCusBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCusCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCustCard)
                            .addComponent(txtCustAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(txtCustBirthDay)
                            .addComponent(txtCustMobile)
                            .addComponent(txtCustFullName)
                            .addComponent(txtCustEmail)
                            .addComponent(txtCustAccountType)
                            .addComponent(txtCustAccountNumber)
                            .addComponent(txtCustSortCode)
                            .addComponent(txtCustBalance))
                        .addGap(0, 12, Short.MAX_VALUE))))
        );
        addCusPanelLayout.setVerticalGroup(
            addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCusPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCusFullName)
                    .addComponent(txtCustFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCusBirthDay)
                    .addComponent(txtCustBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCusAddress)
                    .addComponent(txtCustAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCusMobile)
                    .addComponent(txtCustMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCusEMail)
                    .addComponent(txtCustEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCusAccountType)
                    .addComponent(txtCustAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCusAccountNumber)
                    .addComponent(txtCustAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCusSortCode)
                    .addComponent(txtCustSortCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCusBalance)
                    .addComponent(txtCustBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCusCard)
                    .addComponent(txtCustCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRetrieveValues)
                    .addComponent(btnToCustomerPage))
                .addContainerGap())
        );

        getContentPane().add(addCusPanel, "card7");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String usrGiven = username.getText();
        String passGiven = password.getText();
        if (service.validateLogin(usrGiven, passGiven)) {
            System.out.println("Login Success!");
            loginPanel.setVisible(false);
            loginSuccessPanel.setVisible(true);
            setEmployeeName();
        }
        // System.out.println(service.hello(usrGiven));

    }//GEN-LAST:event_loginBtnActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        username.setText("");
        password.setText("");
    }//GEN-LAST:event_resetBtnActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void manageEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeesActionPerformed
        //empTable.addRowSelectionInterval(0, 10);
        loginSuccessPanel.setVisible(false);
        initiateManageEmpPanel();


    }//GEN-LAST:event_manageEmployeesActionPerformed

    private void empTableInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_empTableInputMethodTextChanged
        System.out.println("Input method text changed");
    }//GEN-LAST:event_empTableInputMethodTextChanged

    private void delEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delEmpBtnActionPerformed
        int[] selection = empTable.getSelectedRows();

        for (int i : selection) {
            int removedID = Integer.parseInt((String) (empTable.getValueAt(i, 0)));
            System.out.println(i + " - " + removedID);
            service.removeEmployee(removedID);
        }
        initiateManageEmpPanel();
        String name;
        System.out.println(service.getSample());
    }//GEN-LAST:event_delEmpBtnActionPerformed

    private void modifyEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyEmpBtnActionPerformed
        empTable.enable(true);

    }//GEN-LAST:event_modifyEmpBtnActionPerformed

    private void saveEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEmpBtnActionPerformed
        try{
        empTable.enable(false);
        int row = empTable.getSelectedRow();
        int changedID = Integer.parseInt((String) empTable.getValueAt(row, 0));
        String changedName = (String) empTable.getValueAt(row, 1);
        String changedPos = (String) empTable.getValueAt(row, 2);
        /*
        List<Employee> empList = service.viewEmployees();
        for (int i = 0; i < empList.size(); i++) {
            if (changedID == empList.get(i).empID) {
                
            }
        }
        */
        
        service.editEmployee(changedID, changedName, changedPos);
        System.out.println(""+changedID+""+changedPos+""+changedName+""+"||"+service.getSample());
        initiateManageEmpPanel();
        }catch(Exception e){
            System.err.println("Found error : "+e );
        }
    }//GEN-LAST:event_saveEmpBtnActionPerformed

    private void addEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmpBtnActionPerformed
        manageEmpPanel.setVisible(false);
        CreateNewEmployee.setVisible(true);
    }//GEN-LAST:event_addEmpBtnActionPerformed

    private void btnCreateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEmployeeActionPerformed
        service.addEmployee(txtFullName.getText(), txtEmployeePosition.getText(), txtUserName.getText(), psswrdFieldEmployee.getText());
        CreateNewEmployee.setVisible(false);
        manageEmpPanel.setVisible(true);
        initiateManageEmpPanel();
    }//GEN-LAST:event_btnCreateEmployeeActionPerformed

    private void btnToEmployeePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToEmployeePageActionPerformed
        manageEmpPanel.setVisible(true);
        CreateNewEmployee.setVisible(false);
    }//GEN-LAST:event_btnToEmployeePageActionPerformed

    private void createEmpResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmpResetBtnActionPerformed
        txtFullName.setText("");
        txtUserName.setText("");
        txtEmployeePosition.setText("");
        psswrdFieldEmployee.setText("");
    }//GEN-LAST:event_createEmpResetBtnActionPerformed

    private void manageCustBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustBtnActionPerformed
        loginSuccessPanel.setVisible(false);
        customerListPanel.setVisible(true);
        customerListPanel.add(logOutBtn);
        initiateCustomerList();
    }//GEN-LAST:event_manageCustBtnActionPerformed

    private void addCusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCusBtnActionPerformed
        addCusPanel.setVisible(true);
        customerListPanel.setVisible(false);
    }//GEN-LAST:event_addCusBtnActionPerformed

    private void txtCustFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustFullNameActionPerformed

    private void btnToCustomerPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToCustomerPageActionPerformed
        addCusPanel.resetKeyboardActions();
        addCusPanel.setVisible(false);
        customerListPanel.setVisible(true);
        

    }//GEN-LAST:event_btnToCustomerPageActionPerformed

    private void btnRetrieveValuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrieveValuesActionPerformed
        cService.addCustomer(txtCustFullName.getText(), txtCustBirthDay.getText(), txtCustAddress.getText(), Long.parseLong(txtCustMobile.getText()), txtCustEmail.getText(), txtCustAccountType.getText(), Long.parseLong(txtCustAccountNumber.getText()),txtCustSortCode.getText(), Double.parseDouble(txtCustBalance.getText()), txtCustCard.getText());
        addCusPanel.setVisible(false);
        initiateCustomerList();
        customerListPanel.setVisible(true);
        System.out.println(cService.getSample());
    }//GEN-LAST:event_btnRetrieveValuesActionPerformed

    private void viewCusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCusBtnActionPerformed
        int row = custListTable.getSelectedRow();
        
    }//GEN-LAST:event_viewCusBtnActionPerformed

    private void delCusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delCusBtnActionPerformed
        int[] selection = custListTable.getSelectedRows();

        for (int i : selection) {
            int removedID = Integer.parseInt((String) (custListTable.getValueAt(i, 0)));
            System.out.println(removedID);
            cService.removeCustomer(removedID);
        }
        initiateCustomerList();
 

    }//GEN-LAST:event_delCusBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        service.setLoginStatus(false);
        //this.setVisible(false);
        loginPanel.setVisible(true);
    }//GEN-LAST:event_logOutBtnActionPerformed
    
    /*Integer.parseInt(txtCustMobile.getText()) Integer.parseInt(txtCustAccountNumber.getText())*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientSide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientSide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientSide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientSide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientSide().setVisible(true);

            }
        });
    }

    public void setEmployeeName() {
        displayName.setText("Employee : " + service.getCurrentUser());

    }
 

    public void initiateManageEmpPanel() {
        setEmployeeName();
        manageEmpPanel.setVisible(true);
        DefaultTableModel model = new DefaultTableModel();
        empTable.setModel(model);
        manageEmpPanel.add(displayName);
        manageEmpPanel.add(logOutBtn);

        model.addColumn("ID");
        model.addColumn("Name");
        model.addColumn("position");

        List<Employee> empList = service.viewEmployees();
        int size = 0;
        size = empList.size();

        for (int i = 0; i < size; i++) {
            String id = empList.get(i).empID + "";
            String name = empList.get(i).empName;
            String pos = empList.get(i).empPosition;
            model.addRow(new String[]{id, name, pos});
        }
        repaint();
        revalidate();
    }
    
    public void initiateCustomerList(){
        setEmployeeName();
        customerListPanel.add(displayName);
        customerListPanel.add(logOutBtn);
        
        DefaultTableModel model = new DefaultTableModel();
        custListTable.setModel(model);
        
        model.addColumn("ID");
        model.addColumn("Name");
        model.addColumn("Account Number");
        
     
        
        List<Customers> cusList = cService.viewCustomers();
        int size = cusList.size();
        
        for(int i = 0;i < size;i++){
            
            model.addRow(new String[]{cusList.get(i).id+"",cusList.get(i).name,cusList.get(i).accountNumber+""});
            
        }
        
        repaint();
        revalidate();   
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateNewEmployee;
    private javax.swing.JButton addCusBtn;
    private javax.swing.JPanel addCusPanel;
    private javax.swing.JButton addEmpBtn;
    private javax.swing.JButton btnCreateEmployee;
    private javax.swing.JButton btnRetrieveValues;
    private javax.swing.JButton btnToCustomerPage;
    private javax.swing.JButton btnToEmployeePage;
    private javax.swing.JButton createEmpResetBtn;
    private javax.swing.JTable custListTable;
    private javax.swing.JPanel customerListPanel;
    private javax.swing.JButton delCusBtn;
    private javax.swing.JButton delEmpBtn;
    private javax.swing.JLabel displayName;
    private javax.swing.JTable empTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCusAccountNumber;
    private javax.swing.JLabel lblCusAccountType;
    private javax.swing.JLabel lblCusAddress;
    private javax.swing.JLabel lblCusBalance;
    private javax.swing.JLabel lblCusBirthDay;
    private javax.swing.JLabel lblCusCard;
    private javax.swing.JLabel lblCusEMail;
    private javax.swing.JLabel lblCusFullName;
    private javax.swing.JLabel lblCusMobile;
    private javax.swing.JLabel lblCusSortCode;
    private javax.swing.JLabel lblEmpFullName;
    private javax.swing.JLabel lblEmpPassword;
    private javax.swing.JLabel lblEmpPossition;
    private javax.swing.JLabel lblEmpUserName;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel loginSuccessPanel;
    private javax.swing.JButton manageCustBtn;
    private javax.swing.JPanel manageEmpPanel;
    private javax.swing.JButton manageEmployees;
    private javax.swing.JButton modifyEmpBtn;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField psswrdFieldEmployee;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveEmpBtn;
    private javax.swing.JTextField txtCustAccountNumber;
    private javax.swing.JTextField txtCustAccountType;
    private javax.swing.JTextField txtCustAddress;
    private javax.swing.JTextField txtCustBalance;
    private javax.swing.JTextField txtCustBirthDay;
    private javax.swing.JTextField txtCustCard;
    private javax.swing.JTextField txtCustEmail;
    private javax.swing.JTextField txtCustFullName;
    private javax.swing.JTextField txtCustMobile;
    private javax.swing.JTextField txtCustSortCode;
    private javax.swing.JTextField txtEmployeePosition;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField username;
    private javax.swing.JButton viewCusBtn;
    // End of variables declaration//GEN-END:variables
}
